### ISSUE TITLE
resize to other size, the result is wrong

### ISSUE THREAD

**Issue by qinxianglinya** [royinx/CUDA_Resize#1]
hello, i find the result is wrong when i resize the image to other size(not 608 x 608), how can i adjust the 'resize.py' to get true result?,Look forward to your reply. thx.

**Comment by royinx** [comment]
it was designed for yolo3_608, 
now updated `resize_free.cu` and `resize_free.py` for free size resizing
will update the transpose and normalise method later on.

**Comment by royinx** [comment]
The transpose and normalise part has been updated.
if you still have the problem, may reopen this issue.

**Comment by qinxianglinya** [comment]
thank you for you reply. i will do a test.
