### ISSUE TITLE
what is the interpolation of this cuda resize?

### ISSUE THREAD

**Issue by osirisQdt** [royinx/CUDA_Resize#8]
what is the interpolation method of your cuda resizing? Could you implement the resizing using INTER_LINEAR, INTER_AREA and INTER_CUBIC interpolation by cuda?

**Comment by royinx** [comment]
This repo implemented Bilinear interpolation, which refers to INTER_LINEAR in OpenCV. 
OpenCV has a slightly different implementation for compatibility which is not necessary for high throughput. 

Area and Cubic are not supported right now while they are not commonly used in my application. 
Implementing algo CUDA is not easy, even this repo is not perfect yet. I will put the highest priority on maximizing the performance with GPU memory

**Comment by osirisQdt** [comment]
> This repo implemented Bilinear interpolation, which refers to INTER_LINEAR in OpenCV. OpenCV has a slightly different implementation for compatibility which is not necessary for high throughput.
> 
> Area and Cubic are not supported right now while they are not commonly used in my application. Implementing algo CUDA is not easy, even this repo is not perfect yet. I will put the highest priority on maximizing the performance with GPU memory

Yea, sorry for slow replying. I am now having to resize images on cuda using different interpolations so it would be great if your algorithm falls into the other two categories :((
